### ISSUE TITLE
about GROND and files in zenodo

### ISSUE THREAD

**Issue by Yesica04** [cazzlewazzle89/GROND#1]
Hello.
I'm  checking the files for download and I see some file with name "refseq207nr_classifierpairA.qza", are this files for use with qiime2? Why are there classifierpairB and C? 

What is the correct file of database? 
this [refseq207full] or this [refseq207nr]? what is the different? 
Thanks.

**Comment by cazzlewazzle89** [comment]
Hi @Yesica04 

Yes these are pre-trained naive-bayes taxonomic classifiers that can be imported directly into qiime2. 

The pair[ABC] models are trained on the regions extracted from the full _rrn_ sequences using the primer pairs evaluated in the GROND manuscript. The qiime2 [tutorial](https://docs.qiime2.org/2024.5/tutorials/feature-classifier/#extract-reference-reads) gives more information, but basically you should train a classifier model using sequences extracted using the same primer sequences that are used to generate the amplicons in your experiment. 

Both the _full_ and _nr_ files are correct, but I would recommend using the _nr_ version (with the taxRep taxonomy labels) for the sake of speed. It is constructed from the full dataset but dereplicated to remove highly similar sequences. For more information see the _Database construction_ and _Taxonomy_ sections in the [manuscript](https://www.microbiologyresearch.org/content/journal/mgen/10.1099/mgen.0.001255). 

If you want a more detailed comparison of taxonomic profiling methods for 16S-ITS-23S data then check out our [preprint](https://www.researchsquare.com/article/rs-4006805/v1).

All the best,
Calum

**Comment by cazzlewazzle89** [comment]
Closing this issue. Feel free to reopen if needed.
