### ISSUE TITLE
classify-consensus-vsearch files

### ISSUE THREAD

**Issue by mls3514** [cazzlewazzle89/GROND#2]
Hi,

Thank you for your paper and the classifier.

I'm using the gtdb207nr_classifierpairC for taxonomy analysis with classify-sklearn but I would like to compare the results using classify-consensus-vsearch. I'm trying to find the reference reads and reference taxonomy .qza files associated with classifierpairC.

Could you please help me with the right files I should use?

Here’s the command I'm planning to run:

qiime feature-classifier classify-consensus-vsearch \
  --i-query rep-seqs.qza \
  --i-reference-reads [reference-reads].qza \
  --i-reference-taxonomy [reference-taxonomy].qza \
  --p-threads 35 \
  --output-dir vsearch_taxonomy \
  --verbose
I appreciate your help!
Thanks

**Comment by cazzlewazzle89** [comment]
Hi,

Thanks for posting this comment.
The input files used to train that particular model are [gtdb207nr_nrRep.fna.gz](https://zenodo.org/records/10889037/files/gtdb207nr_nrRep.fna.gz?download=1) and [gtdb207nr_taxRep.tsv](https://zenodo.org/records/10889037/files/gtdb207nr_taxRep.tsv?download=1).

All nr classifiers are trained using the corresponding nrRep taxonomy - I probably should have made that more explicit in the manuscript. 

The commands used are as follows - where `$1` are BASH positional arguments directing to the sequence and taxonomy files.

```
qiime feature-classifier extract-reads \
      --i-sequences $1 \
      --p-f-primer AGRGTTTGATYHTGGCTCAG \
      --p-r-primer CCRAMCTGTCTCACGACG \
      --p-min-length 1000 \
      --o-reads reads_pairC.qza

qiime feature-classifier fit-classifier-naive-bayes \
  --i-reference-reads reads_pairC.qza \
  --i-reference-taxonomy $1 \
  --o-classifier classifier_pairC.qza
```

All the best,
Calum

**Comment by mls3514** [comment]
Thanks a lot,
Best,
MLuisa
